# Generated by Django 4.0.3 on 2022-05-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_post',
            field=models.ManyToManyField(blank=True, null=True, to='streamapp.commentpost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_post',
            field=models.ManyToManyField(blank=True, null=True, to='streamapp.likepost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='share_post',
            field=models.ManyToManyField(blank=True, null=True, to='streamapp.sharepost'),
        ),
    ]
