# Generated by Django 4.0.3 on 2022-05-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0002_alter_post_comment_post_alter_post_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_post',
            field=models.ImageField(upload_to='<django.db.models.fields.DateTimeField>'),
        ),
    ]
